dev_task/urls.py
from django.conf.urls import url, include
from task import taskurls, views


urlpatterns = [
    url(r'^$', views.Dashboard.as_view(), name="index"),
    url(r'^task/', include(taskurls)),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
]

supply/django-celery-results-master/t/proj/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

task/models.py
# -*- coding:utf-8 -*-

from __future__ import unicode_literals
from django.db import models
from django_celery_beat.models import PeriodicTask


class TimedTask(PeriodicTask):
    nice_name = models.CharField(max_length=255, default='', blank=True)
    host = models.CharField(max_length=255, blank=True, null=True)
    email = models.EmailField(max_length=50, verbose_name=u"邮箱")
    is_send_email = models.BooleanField(default=True, db_index=True, editable=False)
    run_status = models.BooleanField(default=True, db_index=True, editable=False)

task/forms.py
# -*- coding:utf-8 -*-

from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True)

task/views.py
# -*- coding:utf-8 -*-

from django_celery_beat.models import IntervalSchedule, CrontabSchedule, PeriodicTask
from dev_task.celery import (rabbitmq_exchange, rabbitmq_routing_key, rabbitmq_queue,
                             rabbitmq_host, rabbitmq_password, rabbitmq_user,rabbitmq_vhost)
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models.signals import pre_save, pre_delete
from django_celery_results.models import TaskResult
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import AccessMixin
from django.contrib import auth
from django.shortcuts import HttpResponseRedirect, HttpResponse
from django.shortcuts import render as my_render
from django.urls import reverse, reverse_lazy
from django.views.decorators.debug import sensitive_post_parameters
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.generic import TemplateView, ListView, CreateView, UpdateView
from django.views.generic.edit import FormView
from django.views.generic.base import View
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext as _
from dev_task.settings import default_email_users
from datetime import datetime
from celery import current_app
from models import TimedTask
from forms import LoginForm
from supply.rabbitmq_api import MQManage
import json
import urllib, urllib2, base64


class LoginRequiredMixin(AccessMixin):

    @method_decorator(login_required(redirect_field_name='next', login_url='/login/'))
    def dispatch(self, request, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)


@method_decorator(sensitive_post_parameters(), name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
@method_decorator(never_cache, name='dispatch')
class LoginView(FormView):
    template_name = 'login.html'
    form_class = LoginForm
    redirect_field_name = 'next'

    def get_context_data(self, **kwargs):
        kwargs = super(LoginView, self).get_context_data(**kwargs)
        kwargs.update({
            'next': self.request.GET.get('next', '')
        })
        return kwargs

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect(reverse('index'))
        else:
            return super(LoginView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        login_form = self.get_form()
        if login_form.is_valid():
            user_name = login_form.cleaned_data['username']
            pass_word = login_form.cleaned_data['password']
            next = request.POST.get('next', '')
            user = authenticate(username=user_name, password=pass_word)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    if next:
                        return HttpResponseRedirect(next)
                    else:
                        return HttpResponseRedirect(reverse('index'))
                else:
                    return my_render(request, "login.html", {"msq": _(u"用户未激活，请联系管理！")})
            else:
                return my_render(request, "login.html", {"msq": _(u"用户验证失败，请联系管理员！")})
        else:
            return my_render(request, "login.html", {"msq": _(u"用户验证失败，请联系管理员！"), "login_form": login_form})


class LogoutView(View):
    def get(self, request):
        auth.logout(request)
        return HttpResponseRedirect("/login/")


# dashboard
class Dashboard(LoginRequiredMixin, View):
    def get(self, request):
        return my_render(request, "index.html", locals())


# api celery worker
class CeleryWorker(LoginRequiredMixin, View):
    def get(self, request):
        requests = urllib2.Request('http://127.0.0.1:5555/dashboard?json=1')
        response = urllib2.urlopen(requests).read()
        return HttpResponse(response)


# api rabbitmq
class Rabbitmq(LoginRequiredMixin, View):
    def get(self, request):
        mq = MQManage()
        mq.create_connection(rabbitmq_host, rabbitmq_user, rabbitmq_password)
        queuelist = json.dumps({"data": [x for x in json.loads(mq.list_queues()) if not x["name"].startswith('celery')]})
        return HttpResponse(queuelist)


# job list
class JobList(LoginRequiredMixin, ListView):
    model = TimedTask
    template_name = "task/job_list.html"
    context_object_name = "jobs_info"


# job add
class JobAdd(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = TimedTask
    fields = '__all__'
    template_name = "task/job_add.html"
    celery_app = current_app
    celery_app.loader.import_default_modules()
    interval_info = IntervalSchedule.objects.all()
    crontab_info = CrontabSchedule.objects.all()

    def get_context_data(self, **kwargs):
        context = {
            "interval_info": IntervalSchedule.objects.all(),
            "crontab_info": CrontabSchedule.objects.all(),
            "tasks": list(sorted(name for name in self.celery_app.tasks if not name.startswith('celery.'))),
            "default_email_user": default_email_users
        }
        kwargs.update(context)
        return super(JobAdd, self).get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        post_data = request.POST
        enabled_value = str(post_data.get("enabled")) == str(True)
        is_send_email_value = str(post_data.get("is_send_email")) == str(True)

        job_data = {
            "nice_name": post_data.get("nice_name", ''),
            "host": post_data.get("host", ''),
            "name": post_data.get("name", ''),
            "task": post_data.get("regtask", ''),
            "interval_id": post_data.get("interval", ''),
            "crontab_id": post_data.get("crontab", ''),
            "args": post_data.get("args", ''),
            "kwargs": post_data.get("kwargs", ''),
            "queue": str(rabbitmq_queue),
            "exchange": rabbitmq_exchange,
            "routing_key": str(rabbitmq_routing_key),
            "expires": None,
            "enabled": enabled_value,
            "run_status": True if enabled_value else False,
            "description": post_data.get("description", ''),
            "email": post_data.get("email"),
            "is_send_email": is_send_email_value
        }
        print job_data
        if job_data['interval_id'] and job_data['crontab_id']:
            error = u"you can only choices one of interval or crontab!"
            interval_info = self.interval_info
            crontab_info = self.crontab_info
            self.celery_app.loader.import_default_modules()
            tasks = list(sorted(name for name in self.celery_app.tasks if not name.startswith('celery.')))
            return my_render(request, "task/job_add.html", locals())
        value = job_data["kwargs"]
        try:
            json.loads(value)
        except ValueError as exc:
            error = u"Unable to parse JSON: %s" % exc
            interval_info = self.interval_info
            crontab_info = self.crontab_info
            self.celery_app.loader.import_default_modules()
            tasks = list(sorted(name for name in self.celery_app.tasks if not name.startswith('celery.')))
            return my_render(request, "task/job_add.html", locals())
        if job_data['args']:
            try:
                json.loads(job_data['args'])
            except Exception as exc:
                error = u"Unable to parse JSON: %s" % exc
                interval_info = self.interval_info
                crontab_info = self.crontab_info
                self.celery_app.loader.import_default_modules()
                tasks = list(sorted(name for name in self.celery_app.tasks if not name.startswith('celery.')))
        try:
            pre_save.send(sender=PeriodicTask, instance=TimedTask)
            TimedTask.objects.create(**job_data)
            msg = u"添加任务成功!"
        except Exception as e:
            error = u"添加任务失败!,{0}".format(e)
        interval_info = self.interval_info
        crontab_info = self.crontab_info
        self.celery_app.loader.import_default_modules()
        tasks = list(sorted(name for name in self.celery_app.tasks if not name.startswith('celery.')))
        return my_render(request, "task/job_add.html", locals())


# job edit
class JobEdit(LoginRequiredMixin, UpdateView):
    model = TimedTask
    pk_url_kwarg = 'id'
    context_object_name = 'job_info'
    template_name = 'task/job_edit.html'
    fields = '__all__'
    celery_app = current_app
    celery_app.loader.import_default_modules()
    interval_info = IntervalSchedule.objects.all()
    crontab_info = CrontabSchedule.objects.all()

    def get_context_data(self, **kwargs):
        kwargs = super(JobEdit, self).get_context_data(**kwargs)
        kwargs.update({
            "interval_info": self.interval_info,
            "crontab_info": self.crontab_info,
            "tasks": list(sorted(name for name in self.celery_app.tasks if not name.startswith('celery.'))),
            "status": 0
        })
        return kwargs

    def get_queryset(self):
        qs = super(JobEdit, self).get_queryset()
        return qs.filter(pk=self.kwargs.get(self.pk_url_kwarg))

    def post(self, request, *args, **kwargs):
        post_data = request.POST
        enabled_value = str(post_data.get("enabled")) == str(True)
        is_send_email_value = str(post_data.get("is_send_email")) == str(True)
        job_data = {
            "nice_name": post_data.get("nice_name", ''),
            "host": post_data.get("host", ''),
            "name": post_data.get("name", ''),
            "interval_id": post_data.get("interval", ''),
            "crontab_id": post_data.get("crontab", ''),
            "args": post_data.get("args", ''),

templates/task/crontab_add.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title">添加Crontab</h3>
            </div>
                {% if error %}
                    <div class="alert alert-warning text-center">
                        {{ error|safe }}
                        <button aria-hidden="true" data-dismiss="alert" class="close" type="button" style="outline: none;">×</button>
                    </div>
                {% endif %}
                {% if msg %}
                    <div class="alert alert-success text-center">
                        {{ msg|safe }}
                        <button aria-hidden="true" data-dismiss="alert" class="close" type="button" style="outline: none;">×</button>
                    </div>
                {% endif %}
            <form method="post" class="form-horizontal">{% csrf_token %}
              <div class="box-body">
                <div class="form-group">
                    <label class="control-label col-sm-2 col-lg-2" for="id_minute">Minute:</label>
                    <div class="col-sm-8 col-lg-8">
                        <input type="text" id="id_minute" name="minute" value="*" class="form-control" maxlength="64" required>
                    </div>
                </div>
                <hr class="hr-line-dashed">
                <div class="form-group">
                    <label class="control-label col-sm-2 col-lg-2" for="id_hour">Hour:</label>
                    <div class="col-sm-8 col-lg-8">
                        <input type="text" id="id_hour" name="hour" value="*" class="form-control" maxlength="64" required>
                    </div>
                </div>
                <hr class="hr-line-dashed">
                <div class="form-group">
                    <label class="control-label col-sm-2 col-lg-2" for="id_day_of_month">Day of month:</label>
                    <div class="col-sm-8 col-lg-8">
                        <input type="text" id="id_day_of_month" name="day_of_month" value="*" class="form-control" maxlength="64" required>
                    </div>
                </div>
                <hr class="hr-line-dashed">
                <div class="form-group">
                    <label class="control-label col-sm-2 col-lg-2" for="id_month_of_year">Month of year:</label>
                    <div class="col-sm-8 col-lg-8">
                        <input type="text" id="id_month_of_year" name="month_of_year" value="*" class="form-control" maxlength="64" required>
                    </div>
                </div>
                <hr class="hr-line-dashed">
                <div class="form-group">
                    <label class="control-label col-sm-2 col-lg-2" for="id_day_of_week">Day of week:</label>
                    <div class="col-sm-8 col-lg-8">
                        <input type="text" id="id_day_of_week" name="day_of_week" value="*" class="form-control" maxlength="64" required>
                    </div>
                </div>
              </div>
              <div class="box-footer">
                  <div class="col-sm-4 col-sm-offset-2">
                      <button type="reset" class="btn btn-default">重置</button>
                      <button type="submit" class="btn btn-info">保存</button>
                  </div>
              </div>
            </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block  scripts-files %}
<script src="{% static 'js/select2.full.min.js' %}"></script>
<script>
$(function () {
    $('.select2').select2();
});
</script>
{% endblock %}

templates/task/crontab_edit.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'layer/layer.js' %}"></script>
    <script src="{% static 'js/select2.full.min.js' %}"></script>
    <script>
    $(function () {
        $('.select2').select2();
    })
    </script>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <form method="post" class="form-horizontal" action="">{% csrf_token %}
                    <div class="box-body">
                        <div class="form-group">
                            <label class="control-label col-sm-2 col-lg-2" for="id_minute">Minute:</label>
                            <div class="col-sm-8 col-lg-8">
                                <input type="text" id="id_minute" name="minute" value="{{ crontab_info.minute }}" class="form-control" maxlength="64" required>
                            </div>
                        </div>
                        <hr class="hr-line-dashed">
                        <div class="form-group">
                            <label class="control-label col-sm-2 col-lg-2" for="id_hour">Hour:</label>
                            <div class="col-sm-8 col-lg-8">
                                <input type="text" id="id_hour" name="hour" value="{{ crontab_info.hour }}" class="form-control" maxlength="64" required>
                            </div>
                        </div>
                        <hr class="hr-line-dashed">
                        <div class="form-group">
                            <label class="control-label col-sm-2 col-lg-2" for="id_day_of_month">Day of month:</label>
                            <div class="col-sm-8 col-lg-8">
                                <input type="text" id="id_day_of_month" name="day_of_month" value="{{ crontab_info.day_of_month }}" class="form-control" maxlength="64" required>
                            </div>
                        </div>
                        <hr class="hr-line-dashed">
                        <div class="form-group">
                            <label class="control-label col-sm-2 col-lg-2" for="id_month_of_year">Month of year:</label>
                            <div class="col-sm-8 col-lg-8">
                                <input type="text" id="id_month_of_year" name="month_of_year" value="{{ crontab_info.month_of_year }}" class="form-control" maxlength="64" required>
                            </div>
                        </div>
                        <hr class="hr-line-dashed">
                        <div class="form-group">
                            <label class="control-label col-sm-2 col-lg-2" for="id_day_of_week">Day of week:</label>
                            <div class="col-sm-8 col-lg-8">
                                <input type="text" id="id_day_of_week" name="day_of_week" value="{{ crontab_info.day_of_week }}" class="form-control" maxlength="64" required>
                            </div>
                        </div>
                      </div>
                    <div class="box-footer">
                        <div class="col-sm-12">
                            <button type="submit" class="btn btn-info" style="float: right">保存</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
</div>
<script type="text/javascript">
    var index = parent.layer.getFrameIndex(window.name);
    var success = {{ status }};
    if ( success == '1' ) {
        parent.$("#handle_status").val('1');
        parent.layer.close(index);
    } else if( success == '2' ) {
        parent.$("#handle_status").val('2');
        parent.layer.close(index);
    }
</script>
</body>
</html>

templates/task/job_add.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title">添加任务</h3>
            </div>
                {% if error %}
                    <div class="alert alert-warning text-center">
                        {{ error|safe }}
                        <button aria-hidden="true" data-dismiss="alert" class="close" type="button" style="outline: none;">×</button>
                    </div>
                {% endif %}
                {% if msg %}
                    <div class="alert alert-success text-center">
                        {{ msg|safe }}
                        <button aria-hidden="true" data-dismiss="alert" class="close" type="button" style="outline: none;">×</button>
                    </div>
                {% endif %}
            <form method="post" class="form-horizontal" id="job_form">{% csrf_token %}
              <div class="box-body">
                <div class="form-group">
                    <label class="control-label col-sm-2 col-lg-2" for="id_nice_name">主机名称:</label>
                    <div class="col-sm-8 col-lg-8">
                        <input type="text" id="id_nice_name" name="nice_name" class="form-control" maxlength="200" required>
                    </div>
                </div>
                <hr class="hr-line-dashed">
                <div class="form-group">
                    <label class="control-label col-sm-2 col-lg-2" for="id_host">主机ip:</label>
                    <div class="col-sm-8 col-lg-8">
                        <input type="text" id="id_host" name="host" class="form-control" maxlength="200">
                    </div>
                </div>
                <hr class="hr-line-dashed">
                <div class="form-group">
                    <label class="control-label col-sm-2 col-lg-2" for="id_name">Task name:</label>
                    <div class="col-sm-8 col-lg-8">
                        <input type="text" id="id_name" name="name" class="form-control" maxlength="200" required>
                        <span class="help-block m-b-none">Task description</span>
                    </div>
                </div>
                <hr class="hr-line-dashed">
                <div class="form-group">
                    <label class="control-label col-sm-2 col-lg-2" for="id_task">Task (custom):</label>
                    <div class="col-sm-8 col-lg-8">
                        <input type="text" id="id_task" name="task" class="form-control" maxlength="200">
                    </div>
                </div>
                <hr class="hr-line-dashed">
                <div class="form-group">
                    <label class="control-label col-sm-2 col-lg-2" for="id_interval">Interval:</label>
                    <div class="col-sm-8 col-lg-8">
                        <select id="id_interval" name="interval" class="form-control select2">
                                <option value="" selected>---------</option>
                               {% for interval in interval_info %}
                                     <option  value="{{ interval.id }}">every&nbsp;&nbsp;&nbsp;&nbsp;{{ interval.every }}&nbsp;&nbsp;&nbsp;&nbsp;{{ interval.period }}</option>
                               {% endfor %}
                        </select>
                    </div>
                </div>
                <hr class="hr-line-dashed">
                <div class="form-group">
                    <label class="control-label col-sm-2 col-lg-2" for="id_crontab">Crontab:</label>
                    <div class="col-sm-8 col-lg-8">
                        <select id="id_crontab" name="crontab" class="form-control select2">
                                <option value="" selected>---------</option>
                               {% for crontab in crontab_info %}
                                     <option  value="{{ crontab.id }}">{{ crontab.minute }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ crontab.hour }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ crontab.day_of_month }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ crontab.month_of_year }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ crontab.day_of_week }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(m/h/dM/MY/d)</option>
                               {% endfor %}
                        </select>
                    <span class="help-block m-b-none">Use one of interval/crontab</span>
                    </div>
                </div>
                <hr class="hr-line-dashed">
                <div class="form-group">
                    <label class="control-label col-sm-2 col-lg-2" for="id_args">Arguments:</label>
                    <div class="col-sm-8 col-lg-8">
                        <input type="text" id="id_args" name="args" value="[]" class="form-control" maxlength="200">
                        <span class="help-block m-b-none">JSON encoded positional arguments</span>
                    </div>
                </div>
                <hr class="hr-line-dashed">
                <div class="form-group">
                    <label class="control-label col-sm-2 col-lg-2" for="id_kwargs">任务指令:</label>
                    <div class="col-sm-8 col-lg-8">
                        <!-- {"task_name":"test2","host":"127.0.0.1","cmd":"ls /home"} -->
                        <input type="text" id="id_kwargs" name="kwargs" placeholder="{&quot;task_name&quot;:&quot;your task name&quot;,&quot;host&quot;:&quot;host's ip&quot;&quot;cmd&quot;:&quot;commands&quot;}" class="form-control" maxlength="200" required>
                    </div>
                </div>
                <hr class="hr-line-dashed">
                <div class="form-group">
                    <label class="control-label col-sm-2 col-lg-2" for="id_enabled">Enabled:</label>
                    <div class="col-sm-8 col-lg-8">
                        <select id="id_enabled" name="enabled" class="form-control select2">
                          <option value="True" selected>启用</option>
                          <option value="False">禁用</option>
                        </select>
                    </div>
                </div>
                <hr class="hr-line-dashed">
                <div class="form-group">
                    <label class="control-label col-sm-2 col-lg-2" for="id_email">Email:</label>
                    <div class="col-sm-8 col-lg-8">
                        <input type="text" id="id_email" name="email" value="{{ default_email_user }}" class="form-control" maxlength="200">
                    </div>
                </div>
                <hr class="hr-line-dashed">
                <div class="form-group">
                    <label class="col-sm-2 control-label">是否允许发送告警邮件:</label>
                    <div class="col-sm-2">
                        <div class="radio radio-inline checkbox">
                            <label><input type="radio" value="False" name="is_send_email" >禁用 </label>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="radio radio-inline checkbox">
                            <label><input type="radio" value="True" name="is_send_email" checked>发送邮件 </label>
                        </div>
                    </div>
                </div>
                <hr class="hr-line-dashed">
                <div class="form-group">
                    <label class="control-label col-sm-2 col-lg-2" for="id_description">Description:</label>
                    <div class="col-sm-8 col-lg-8">
                        <textarea name="description" id="id_description" class="form-control"></textarea>
                    </div>
                </div>
                <hr class="hr-line-dashed">
                <div class="form-group">
                    <label  class="control-label col-sm-2 col-lg-2" for="id_regtask">Task (registered):</label>
                    <div class="col-sm-8 col-lg-8">
                        <select id="id_regtask" name="regtask" class="form-control select2">
                                <option value="" selected>---------</option>
                               {% for task in tasks %}
                                     <option value="{{ task }}">&nbsp;&nbsp;{{ task }}</option>
                               {% endfor %}
                        </select>
                    </div>
                </div>
              </div>
              <div class="box-footer">
                  <div class="col-sm-4 col-sm-offset-2">
                      <button type="reset" class="btn btn-default">重置</button>
                      <button type="submit" class="btn btn-info">保存</button>
                  </div>
              </div>
            </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts-files %}
    <script>
        $(function () {
            $('.select2').select2();
        })
    </script>
    <script>
    $(document).ready(function () {
        jQuery.validator.addMethod("ip", function(value, element) {
            var ip = /^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)/;
            return this.optional(element) || (ip.test(value));
        }, "Ip地址格式错误");
        $('#job_form').validate({
            rules: {
                host: {
                    required : true,
                    minlength : 7,
                    ip : true
                }
            },
            messages: {
                host: {
                    required: "请输入ip",
                    minlength: "IP至少由7个字母组成"
                }
            }

        });
    });
    </script>
{% endblock %}